#!/bin/bash

# Chatzilla Tor Hidden Service Setup Script
# This script configures the system to run Chatzilla as a Tor hidden service

set -e

echo "🧅 Chatzilla Tor Hidden Service Setup"
echo "======================================"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run as root for Tor configuration"
   echo "   Run with: sudo ./setup_tor_service.sh"
   exit 1
fi

# Install Tor if not present
if ! command -v tor &> /dev/null; then
    echo "📦 Installing Tor..."
    apt update
    apt install -y tor
    echo "✅ Tor installed successfully"
else
    echo "✅ Tor is already installed"
fi

# Create Tor configuration directory
TOR_HIDDEN_DIR="/var/lib/tor/chatzilla_hidden_service"
echo "📁 Creating Tor hidden service directory..."

# Stop Tor service to modify configuration
systemctl stop tor 2>/dev/null || true

# Backup original torrc
if [ ! -f /etc/tor/torrc.backup ]; then
    cp /etc/tor/torrc /etc/tor/torrc.backup
    echo "💾 Backed up original torrc"
fi

# Create new torrc configuration
cat > /etc/tor/torrc << 'EOF'
# Chatzilla Tor Hidden Service Configuration
# Generated by Chatzilla setup script

# Basic Tor configuration
SocksPort 9050
ControlPort 9051
DataDirectory /var/lib/tor

# Hidden service configuration for Chatzilla
HiddenServiceDir /var/lib/tor/chatzilla_hidden_service/
HiddenServicePort 80 127.0.0.1:3000      # Frontend
HiddenServicePort 8001 127.0.0.1:8001    # Backend API

# Security settings
HiddenServiceVersion 3                     # Use v3 onion addresses (56 characters)
HiddenServiceNonAnonymousMode 0           # Keep anonymity enabled
HiddenServiceSingleHopMode 0              # Use full Tor circuit for security

# Performance and reliability
HiddenServiceNumIntroductionPoints 5      # More introduction points for reliability
HiddenServiceMaxStreams 100               # Allow more concurrent connections
HiddenServiceMaxStreamsCloseCircuit 1     # Close circuit on stream limit

# Security hardening
DisableAllSwap 1                          # Prevent memory swapping
HardwareAccel 0                           # Disable hardware acceleration for security
SafeLogging 1                             # Enable safe logging (no sensitive data)

# Network settings
CircuitBuildTimeout 60                    # Longer timeout for stability
LearnCircuitBuildTimeout 0                # Don't learn from build times
MaxCircuitDirtiness 300                   # 5 minutes max circuit lifetime

# Client connections
SocksTimeout 120                          # 2 minute timeout for SOCKS connections
ClientOnly 1                              # Act as client only (not relay)

# Logging
Log notice file /var/log/tor/notices.log
Log warn file /var/log/tor/warn.log

# Additional security
CookieAuthentication 1                    # Enable cookie authentication for control port
CookieAuthFileGroupReadable 1            # Allow group read for control auth
EOF

echo "📝 Created Tor configuration"

# Set proper permissions
chown -R debian-tor:debian-tor /var/lib/tor/
chmod -R 700 /var/lib/tor/
chown debian-tor:debian-tor /etc/tor/torrc
chmod 644 /etc/tor/torrc

# Create log directory
mkdir -p /var/log/tor
chown debian-tor:debian-tor /var/log/tor
chmod 755 /var/log/tor

echo "🔐 Set proper permissions"

# Start Tor service
echo "🚀 Starting Tor service..."
systemctl enable tor
systemctl start tor

# Wait for hidden service to be created
echo "⏳ Waiting for hidden service to be generated (this may take a few minutes)..."
sleep 10

# Check if hostname file exists and wait if needed
counter=0
while [ ! -f "$TOR_HIDDEN_DIR/hostname" ] && [ $counter -lt 60 ]; do
    echo "   Waiting for hidden service generation... ($counter/60)"
    sleep 5
    counter=$((counter + 5))
done

if [ -f "$TOR_HIDDEN_DIR/hostname" ]; then
    ONION_ADDRESS=$(cat "$TOR_HIDDEN_DIR/hostname")
    echo ""
    echo "🎉 SUCCESS! Your Chatzilla hidden service is ready!"
    echo "=============================================="
    echo ""
    echo "🧅 Your .onion address is:"
    echo "   $ONION_ADDRESS"
    echo ""
    echo "📋 Next steps:"
    echo "   1. Update your environment files with this address"
    echo "   2. Restart your Chatzilla application"
    echo "   3. Access via Tor Browser at: http://$ONION_ADDRESS"
    echo ""
    
    # Create environment update script
    cat > /app/update_tor_env.sh << EOF
#!/bin/bash
# Update environment files for Tor hidden service

ONION_ADDRESS="$ONION_ADDRESS"

echo "Updating environment files with onion address..."

# Update backend .env
echo "" >> /app/backend/.env
echo "# Tor Hidden Service Configuration" >> /app/backend/.env
echo "TOR_ENABLED=true" >> /app/backend/.env
echo "ONION_ADDRESS=\$ONION_ADDRESS" >> /app/backend/.env
echo "ALLOW_ONION_ORIGINS=true" >> /app/backend/.env

# Update frontend .env
cp /app/frontend/.env /app/frontend/.env.backup
sed -i "s|REACT_APP_BACKEND_URL=.*|REACT_APP_BACKEND_URL=http://\$ONION_ADDRESS:8001|" /app/frontend/.env
echo "" >> /app/frontend/.env
echo "# Tor Hidden Service Configuration" >> /app/frontend/.env
echo "REACT_APP_TOR_ENABLED=true" >> /app/frontend/.env

echo "✅ Environment files updated!"
echo "🔄 Please restart your Chatzilla services:"
echo "   sudo supervisorctl restart all"
EOF
    
    chmod +x /app/update_tor_env.sh
    echo "   4. Run: /app/update_tor_env.sh (to update environment files)"
    
else
    echo "❌ Failed to generate hidden service. Check Tor logs:"
    echo "   sudo journalctl -u tor -f"
    exit 1
fi

# Create monitoring script
cat > /app/monitor_tor.sh << 'EOF'
#!/bin/bash
# Monitor Tor hidden service health

echo "🧅 Chatzilla Tor Hidden Service Status"
echo "======================================"

# Check Tor service status
echo "🔍 Tor Service Status:"
if systemctl is-active --quiet tor; then
    echo "   ✅ Tor service is running"
else
    echo "   ❌ Tor service is not running"
    echo "   Try: sudo systemctl start tor"
fi

# Check hidden service
if [ -f "/var/lib/tor/chatzilla_hidden_service/hostname" ]; then
    ONION_ADDRESS=$(cat /var/lib/tor/chatzilla_hidden_service/hostname)
    echo "   ✅ Hidden service configured: $ONION_ADDRESS"
    
    # Test if service is reachable
    echo ""
    echo "🌐 Testing Service Accessibility:"
    if command -v curl &> /dev/null; then
        if timeout 30 curl -s --socks5 127.0.0.1:9050 "http://$ONION_ADDRESS/api/health" > /dev/null; then
            echo "   ✅ Hidden service is accessible via Tor"
        else
            echo "   ⚠️  Hidden service may not be accessible (check if app is running)"
        fi
    else
        echo "   ℹ️  Install curl to test accessibility"
    fi
else
    echo "   ❌ Hidden service not found"
fi

# Check recent Tor logs
echo ""
echo "📋 Recent Tor Activity:"
if [ -f "/var/log/tor/notices.log" ]; then
    echo "   Last 5 log entries:"
    tail -n 5 /var/log/tor/notices.log | sed 's/^/   /'
else
    echo "   No log file found"
fi

# Show resource usage
echo ""
echo "💾 Resource Usage:"
echo "   Tor processes: $(pgrep -c tor || echo 0)"
if command -v ps &> /dev/null; then
    echo "   Memory usage: $(ps -p $(pgrep tor) -o rss= 2>/dev/null | awk '{sum+=$1} END {printf "%.1f MB\n", sum/1024}' 2>/dev/null || echo "N/A")"
fi

echo ""
echo "🔗 Access your service at: http://$ONION_ADDRESS"
echo "📖 View full logs: sudo journalctl -u tor -f"
EOF

chmod +x /app/monitor_tor.sh

echo ""
echo "📊 Additional tools created:"
echo "   - /app/update_tor_env.sh (update environment files)"
echo "   - /app/monitor_tor.sh (monitor service health)"
echo ""
echo "⚠️  IMPORTANT SECURITY NOTES:"
echo "   - Backup your Tor keys: /var/lib/tor/chatzilla_hidden_service/"
echo "   - Keep your system updated for security"
echo "   - Monitor logs regularly for suspicious activity"
echo "   - Follow responsible disclosure for any security issues"
echo ""
echo "📚 For more information, see: /app/TOR_HIDDEN_SERVICE_GUIDE.md"
echo ""
echo "🎯 Setup complete! Your secure, anonymous chat service is ready."